Filename : notebook_03.ipynb <br>
Description : Workshop 1 - Finding insights in the data

---

In [3]:
import numpy as np
import pandas as pd

<small>1. Read the ifood.xlsx file using Pandas and store it in the variable df

In [4]:
df = pd.read_excel("../Week02/ifood.xlsx")

<small>2. Display the first 5 records and the first 10 records of the dataset.

In [5]:
df.head()
df.head(10)

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
0,1,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,1,63,2822,Single,Graduation
1,2,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,3,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,4,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,5,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PhD
5,6,62513,0,1,16,520,42,98,0,42,...,0,0,0,0,0,0,53,2452,Together,Master
6,7,55635,0,1,34,235,65,164,50,49,...,0,0,0,0,0,0,49,2752,Divorced,Graduation
7,8,33454,1,0,32,76,10,56,3,1,...,0,0,0,0,0,0,35,2576,Married,PhD
8,9,30351,1,0,19,14,0,24,3,3,...,0,0,0,0,0,1,46,2547,Together,PhD
9,10,5648,1,1,68,28,0,6,1,1,...,0,0,0,0,0,0,70,2267,Together,PhD

<small>3. Display the last 5 records of the dataset.

In [6]:
df.tail()

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
2200,2201,61223,0,1,46,709,43,182,42,118,...,0,0,0,0,0,0,53,2540,Married,Graduation
2201,2202,64014,2,1,56,406,0,30,0,0,...,0,0,1,0,0,0,74,2178,Together,PhD
2202,2203,56981,0,0,91,908,48,217,32,12,...,1,0,0,0,0,0,39,2314,Divorced,Graduation
2203,2204,69245,0,1,8,428,30,214,80,30,...,0,0,0,0,0,0,64,2315,Together,Master
2204,2205,52869,1,1,40,84,3,61,2,1,...,0,0,0,0,0,1,66,2781,Married,PhD

<small>4. Check the following: (1) Number of records, (2) Number of columns, (3) Data type of each column, (4) Number of non-null values

In [7]:
print("Number of records:", df.shape[0])
print("Number of columns:", df.shape[1])
print(df.dtypes)
print(df.notna().sum())

Number of records: 2205
Number of columns: 27
No                      int64
Income                  int64
Kidhome                 int64
Teenhome                int64
Recency                 int64
MntWines                int64
MntFruits               int64
MntMeatProducts         int64
MntFishProducts         int64
MntSweetProducts        int64
MntGoldProds            int64
NumDealsPurchases       int64
NumWebPurchases         int64
NumCatalogPurchases     int64
NumStorePurchases       int64
NumWebVisitsMonth       int64
AcceptedCmp3            int64
AcceptedCmp4            int64
AcceptedCmp5            int64
AcceptedCmp1            int64
AcceptedCmp2            int64
Complain                int64
Response                int64
Age                     int64
Customer_Days           int64
Marital                object
Education              object
dtype: object
No                     2205
Income                 2205
Kidhome                2205
Teenhome               2205
Recency                2205
MntWines               2205
MntFruits              2205
MntMeatProducts        2205
MntFishProducts        2205
MntSweetProducts       2205
MntGoldProds           2205
NumDealsPurchases      2205
NumWebPurchases        2205
NumCatalogPurchases    2205
NumStorePurchases      2205
NumWebVisitsMonth      2205
AcceptedCmp3           2205
AcceptedCmp4           2205
AcceptedCmp5           2205
AcceptedCmp1           2205
AcceptedCmp2           2205
Complain               2205
Response               2205
Age                    2205
Customer_Days          2205
Marital                2205
Education              2205
dtype: int64

<small>5. Display the descriptive statistics of the numerical columns, including at least: (1) Mean, (2) Standard deviation, (3) Minimum, (4) Maximum

In [8]:
df.describe()
df.describe().loc[['mean', 'std', 'min', 'max']]

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days
mean,1103.000000,51622.094785,0.442177,0.506576,49.009070,306.164626,26.403175,165.312018,37.756463,27.128345,...,5.336961,0.073923,0.074376,0.073016,0.064399,0.013605,0.009070,0.15102,51.095692,2512.718367
std,636.672993,20713.063826,0.537132,0.544380,28.932111,337.493839,39.784484,217.784507,54.824635,41.130468,...,2.413535,0.261705,0.262442,0.260222,0.245518,0.115872,0.094827,0.35815,11.705801,202.563647
min,1.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,24.000000,2159.000000
max,2205.000000,113734.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,262.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,80.000000,2858.000000

<small>6. Select and display only column "Income"

In [9]:
df['Income']
df2 = df['Income']
df3 = df[['Income']]

<small>7. Select and display following columns: "Age", "Income", "Education", "Marital"

In [10]:
df[["Age", "Income", "Education"]]

      Age  Income   Education
0      63   58138  Graduation
1      66   46344  Graduation
2      55   71613  Graduation
3      36   26646  Graduation
4      39   58293         PhD
...   ...     ...         ...
2200   53   61223  Graduation
2201   74   64014         PhD
2202   39   56981  Graduation
2203   64   69245      Master
2204   66   52869         PhD

[2205 rows x 3 columns]

<small>8. Create new DataFrame consisting of "No", "Age", "Income", "Kidhome", "Teenhome", "Marital"

In [11]:
new_df = df[["No", "Age", "Income", "Kidhome", "Teenhome", "Marital"]]
new_df

        No  Age  Income  Kidhome  Teenhome   Marital
0        1   63   58138        0         0    Single
1        2   66   46344        1         1    Single
2        3   55   71613        0         0  Together
3        4   36   26646        1         0  Together
4        5   39   58293        1         0   Married
...    ...  ...     ...      ...       ...       ...
2200  2201   53   61223        0         1   Married
2201  2202   74   64014        2         1  Together
2202  2203   39   56981        0         0  Divorced
2203  2204   64   69245        0         1  Together
2204  2205   66   52869        1         1   Married

[2205 rows x 6 columns]

<small>9. Use .loc[ ] to select records with index values from 100 to 109 and display only the following columns: "No", "Age", "Income"<small>

In [12]:
df.loc[100:109, ["No", "Age", "Income"]]

      No  Age  Income
100  101   60   89058
101  102   41   77298
102  103   29   68126
103  104   57   57288
104  105   29   86037
105  106   40   43974
106  107   58   50785
107  108   50   90765
108  109   42   36550
109  110   53   30753

<small>10. Use .iloc[ ] to select records 100–109 columns 1–5

In [13]:
df.iloc[100:110, 1:6]

     Income  Kidhome  Teenhome  Recency  MntWines
100   89058        0         0       18       454
101   77298        0         1       46       425
102   68126        0         0       40      1332
103   57288        0         1       27       527
104   86037        0         0       95       490
105   43974        1         0       19       378
106   50785        1         1       27        64
107   90765        0         0       25       547
108   36550        1         0       74        47
109   30753        1         1       85        12

<small>11. Select only customers who are older than 40 years. Display: "No", "Age", "Income", "Response".

In [14]:
df.loc[df["Age"] > 40, ["No", "Age", "Income", "Response"]]     # more standard
#df[df["Age"] > 40][["No", "Age", "Income", "Response"]]         # old school

        No  Age  Income  Response
0        1   63   58138         1
1        2   66   46344         0
2        3   55   71613         0
5        6   53   62513         0
6        7   49   55635         0
...    ...  ...     ...       ...
2199  2200   46   34421         0
2200  2201   53   61223         0
2201  2202   74   64014         0
2203  2204   64   69245         0
2204  2205   66   52869         1

[1787 rows x 4 columns]

<small> 12. Select only customers whose Income is greater than 50,000. Display: "No", "Age“, "Income“.

In [15]:
df.loc[df["Income"] > 50000, ["No", "Age", "Income"]]

        No  Age  Income
0        1   63   58138
2        3   55   71613
4        5   39   58293
5        6   53   62513
6        7   49   55635
...    ...  ...     ...
2200  2201   53   61223
2201  2202   74   64014
2202  2203   39   56981
2203  2204   64   69245
2204  2205   66   52869

[1146 rows x 3 columns]

<small>13. Select only customers who meet both conditions: "Age" > 40, "Income" > 50,000

In [16]:
df.loc[(df["Age"] > 40) & (df["Income"] > 50000), ["No", "Age", "Income"]]

        No  Age  Income
0        1   63   58138
2        3   55   71613
5        6   53   62513
6        7   49   55635
11      12   61   63033
...    ...  ...     ...
2194  2195   58   57967
2200  2201   53   61223
2201  2202   74   64014
2203  2204   64   69245
2204  2205   66   52869

[983 rows x 3 columns]

<small> 14. Select only customers who meet either of the following conditions: "Kidhome" > 0 or "Teenhome" > 0. Display:  "No",  "Kidhome", "Teenhome".

In [17]:
df.loc[(df["Kidhome"] > 0) | (df["Teenhome"] > 0), ["No", "Kidhome", "Teenhome"]]

        No  Kidhome  Teenhome
1        2        1         1
3        4        1         0
4        5        1         0
5        6        0         1
6        7        0         1
...    ...      ...       ...
2199  2200        1         0
2200  2201        0         1
2201  2202        2         1
2203  2204        0         1
2204  2205        1         1

[1577 rows x 3 columns]

<small> 15. Select only customers who accepted the offer in both Campaign 1 and Campaign 2. Conditions: "AcceptedCmp1"== 1 and "AcceptedCmp2" == 1 "Display": "No", "AcceptedCmp1", "AcceptedCmp2", "Response"

In [18]:
df.loc[(df["AcceptedCmp1"] == 1) & (df["AcceptedCmp2"] == 1), 
       ["No", "AcceptedCmp1", "AcceptedCmp2", "Response"]]

        No  AcceptedCmp1  AcceptedCmp2  Response
238    239             1             1         1
400    401             1             1         0
413    414             1             1         1
542    543             1             1         1
558    559             1             1         1
784    785             1             1         1
804    805             1             1         1
970    971             1             1         1
1067  1068             1             1         1
1287  1288             1             1         1
1684  1685             1             1         1
1896  1897             1             1         1
2134  2135             1             1         1

<small>16. Set "No" as the index of the DataFrame. Then display the first 10 records.

In [19]:
df = df.set_index("No")
print(df)

      Income  Kidhome  Teenhome  Recency  MntWines  MntFruits  \
No
1      58138        0         0       58       635         88
2      46344        1         1       38        11          1
3      71613        0         0       26       426         49
4      26646        1         0       26        11          4
5      58293        1         0       94       173         43
...      ...      ...       ...      ...       ...        ...
2201   61223        0         1       46       709         43
2202   64014        2         1       56       406          0
2203   56981        0         0       91       908         48
2204   69245        0         1        8       428         30
2205   52869        1         1       40        84          3

      MntMeatProducts  MntFishProducts  MntSweetProducts  MntGoldProds  ...  \
No                                                                      ...
1                 546              172                88            88  ...
2                   6                2                 1             6  ...
3                 127              111                21            42  ...
4                  20               10                 3             5  ...
5                 118               46                27            15  ...
...               ...              ...               ...           ...  ...
2201              182               42               118           247  ...
2202               30                0                 0             8  ...
2203              217               32                12            24  ...
2204              214               80                30            61  ...
2205               61                2                 1            21  ...

      AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
No
1                0             0             0             0         0
2                0             0             0             0         0
3                0             0             0             0         0
4                0             0             0             0         0
5                0             0             0             0         0
...            ...           ...           ...           ...       ...
2201             0             0             0             0         0
2202             0             0             1             0         0
2203             1             0             0             0         0
2204             0             0             0             0         0
2205             0             0             0             0         0

      Response  Age  Customer_Days   Marital   Education
No
1            1   63           2822    Single  Graduation
2            0   66           2272    Single  Graduation
3            0   55           2471  Together  Graduation
4            0   36           2298  Together  Graduation
5            0   39           2320   Married         PhD
...        ...  ...            ...       ...         ...
2201         0   53           2540   Married  Graduation
2202         0   74           2178  Together         PhD
2203         0   39           2314  Divorced  Graduation
2204         0   64           2315  Together      Master
2205         1   66           2781   Married         PhD

[2205 rows x 26 columns]

<small>17. Using the DataFrame from Exercise 16, restore "No" as a column.

In [20]:
df = df.reset_index()
df

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
0,1,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,1,63,2822,Single,Graduation
1,2,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,3,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,4,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,5,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PhD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2201,61223,0,1,46,709,43,182,42,118,...,0,0,0,0,0,0,53,2540,Married,Graduation
2201,2202,64014,2,1,56,406,0,30,0,0,...,0,0,1,0,0,0,74,2178,Together,PhD
2202,2203,56981,0,0,91,908,48,217,32,12,...,1,0,0,0,0,0,39,2314,Divorced,Graduation
2203,2204,69245,0,1,8,428,30,214,80,30,...,0,0,0,0,0,0,64,2315,Together,Master
2204,2205,52869,1,1,40,84,3,61,2,1,...,0,0,0,0,0,1,66,2781,Married,PhD

<small>18. Check the number of missing values in each column and identify the column with the most missing values.

In [21]:
missing_counts = df.isnull().sum()
missing_counts

No                     0
Income                 0
Kidhome                0
Teenhome               0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Response               0
Age                    0
Customer_Days          0
Marital                0
Education              0
dtype: int64

<small>19.Remove records containing missing values and compare the number of records: * Before removal* After removal* Number of records removed

In [22]:
before = len(df)
df_clean = df.dropna()
after = len(df_clean)
removed = before - after
print("Before removal:", before)
print("After removal:", after)
print("Number of records removed:", removed)

Before removal: 2205
After removal: 2205
Number of records removed: 0

<small>20. Create a new DataFrame and replace missing values in `Income` with the mean value of `Income`.

In [23]:
mean_income = df["Income"].mean()
new_df = df.copy()
new_df["Income"] = new_df["Income"].fillna(mean_income)
print(new_df.head())

   No  Income  Kidhome  Teenhome  Recency  MntWines  MntFruits  \
0   1   58138        0         0       58       635         88
1   2   46344        1         1       38        11          1
2   3   71613        0         0       26       426         49
3   4   26646        1         0       26        11          4
4   5   58293        1         0       94       173         43

   MntMeatProducts  MntFishProducts  MntSweetProducts  ...  AcceptedCmp4  \
0              546              172                88  ...             0
1                6                2                 1  ...             0
2              127              111                21  ...             0
3               20               10                 3  ...             0
4              118               46                27  ...             0

   AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  Response  Age  \
0             0             0             0         0         1   63
1             0             0             0         0         0   66
2             0             0             0         0         0   55
3             0             0             0         0         0   36
4             0             0             0         0         0   39

   Customer_Days   Marital   Education
0           2822    Single  Graduation
1           2272    Single  Graduation
2           2471  Together  Graduation
3           2298  Together  Graduation
4           2320   Married         PhD

[5 rows x 27 columns]

<small>21. Rename the following columns: "MntWines" → "Wine_Spending", "MntMeatProducts" → "Meat_Spending", "MntFishProducts" → "Fish_Spending"

In [24]:
df = df.rename(columns={
    "MntWines": "Wine_Spending",
    "MntMeatProducts": "Meat_Spending",
    "MntFishProducts": "Fish_Spending"
})

print(df.head())

   No  Income  Kidhome  Teenhome  Recency  Wine_Spending  MntFruits  \
0   1   58138        0         0       58            635         88
1   2   46344        1         1       38             11          1
2   3   71613        0         0       26            426         49
3   4   26646        1         0       26             11          4
4   5   58293        1         0       94            173         43

   Meat_Spending  Fish_Spending  MntSweetProducts  ...  AcceptedCmp4  \
0            546            172                88  ...             0
1              6              2                 1  ...             0
2            127            111                21  ...             0
3             20             10                 3  ...             0
4            118             46                27  ...             0

   AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  Response  Age  \
0             0             0             0         0         1   63
1             0             0             0         0         0   66
2             0             0             0         0         0   55
3             0             0             0         0         0   36
4             0             0             0         0         0   39

   Customer_Days   Marital   Education
0           2822    Single  Graduation
1           2272    Single  Graduation
2           2471  Together  Graduation
3           2298  Together  Graduation
4           2320   Married         PhD

[5 rows x 27 columns]

<small> 22.Create a new DataFrame by removing unnecessary columns, such as: "No", "Customer_Days"

In [25]:
new_df = df.drop(columns=["No", "Customer_Days"])
new_df

,Income,Kidhome,Teenhome,Recency,Wine_Spending,MntFruits,Meat_Spending,Fish_Spending,MntSweetProducts,MntGoldProds,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Marital,Education
0,58138,0,0,58,635,88,546,172,88,88,...,0,0,0,0,0,0,1,63,Single,Graduation
1,46344,1,1,38,11,1,6,2,1,6,...,0,0,0,0,0,0,0,66,Single,Graduation
2,71613,0,0,26,426,49,127,111,21,42,...,0,0,0,0,0,0,0,55,Together,Graduation
3,26646,1,0,26,11,4,20,10,3,5,...,0,0,0,0,0,0,0,36,Together,Graduation
4,58293,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,0,39,Married,PhD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,61223,0,1,46,709,43,182,42,118,247,...,0,0,0,0,0,0,0,53,Married,Graduation
2201,64014,2,1,56,406,0,30,0,0,8,...,0,0,0,1,0,0,0,74,Together,PhD
2202,56981,0,0,91,908,48,217,32,12,24,...,0,1,0,0,0,0,0,39,Divorced,Graduation
2203,69245,0,1,8,428,30,214,80,30,61,...,0,0,0,0,0,0,0,64,Together,Master
2204,52869,1,1,40,84,3,61,2,1,21,...,0,0,0,0,0,0,1,66,Married,PhD

<small>23. Inspect the values in the "Education" column and then replace: Graduation → Graduate, PhD → Doctorate.

In [26]:
# ตรวจสอบค่าที่มีในคอลัมน์ Education
print(df["Education"].unique())

# แทนค่า Graduation → Graduate, PhD → Doctorate
df["Education"] = df["Education"].replace({
    "Graduation": "Graduate",
    "PhD": "Doctorate"
})

print(df["Education"].unique())

['Graduation' 'PhD' 'Master' 'Basic' '2nCycle']
['Graduate' 'Doctorate' 'Master' 'Basic' '2nCycle']

<small>24. Check whether the dataset contains duplicate records. Report: (A) Number of duplicate records, (B) Duplicate records found

In [27]:
duplicates = df[df.duplicated()]

# รายงานผล
print("A) Number of duplicate records:", duplicates.shape[0])
print("B) Duplicate records found:")
print(duplicates)

A) Number of duplicate records: 0
B) Duplicate records found:
Empty DataFrame
Columns: [No, Income, Kidhome, Teenhome, Recency, Wine_Spending, MntFruits, Meat_Spending, Fish_Spending, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonth, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5, AcceptedCmp1, AcceptedCmp2, Complain, Response, Age, Customer_Days, Marital, Education]
Index: []

[0 rows x 27 columns]

<small> 25. Remove duplicate records from the dataset and then check whether any duplicates remain.

In [28]:
# ลบเรคคอร์ดที่ซ้ำกัน
df_no_duplicates = df.drop_duplicates()

# ตรวจสอบว่ามีเรคคอร์ดซ้ำเหลืออยู่หรือไม่
duplicates_remaining = df_no_duplicates.duplicated().sum()

print("Number of duplicates remaining:", duplicates_remaining)

Number of duplicates remaining: 0

<small>26. Check the data type of "Customer_Days" and then change its data type to an appropriate date-related data type and check the result again.

In [29]:
# ตรวจสอบชนิดข้อมูลของ Customer_Days
print("Before:", df["Customer_Days"].dtype)

# แปลงเป็นชนิดข้อมูลวันที่
df["Customer_Days"] = pd.to_datetime(df["Customer_Days"], errors="coerce")

# ตรวจสอบอีกครั้ง
print("After:", df["Customer_Days"].dtype)

Before: int64
After: datetime64[ns]

<small> 27.Create a new column named "Response_Label" based on "Response": 1 → Accepted, 0 → Not Accepted

In [30]:
df["Response_Label"] = df["Response"].map({1: "Accepted", 0: "Not Accepted"})

print(df[["Response", "Response_Label"]].head())

   Response Response_Label
0         1       Accepted
1         0   Not Accepted
2         0   Not Accepted
3         0   Not Accepted
4         0   Not Accepted

<small>28. Divide customers into three groups: (1) Income < 30,000 → Low, (2) 30,000–60,000 → Medium, (3) Income > 60,000 → High

In [31]:
df["Income_Group"] = np.where(df["Income"] < 30000, "Low",
                      np.where(df["Income"] <= 60000, "Medium", "High"))

print(df[["Income", "Income_Group"]].head())

   Income Income_Group
0   58138       Medium
1   46344       Medium
2   71613         High
3   26646          Low
4   58293       Medium

<small> 29. Group customers by "Education" and calculate: (1) Number of customers, (2) Average Income, (3) Average Age, (4) Average Wine Spending, (5) Average Web Purchases, (6) Average Store Purchases

In [32]:
grouped = df.groupby("Education").agg({
    "No": "count",
    "Income": "mean",
    "Age": "mean",
    "MntWines": "mean",
    "NumWebPurchases": "mean",
    "NumStorePurchases": "mean"
}).rename(columns={
    "No": "Number_of_Customers",
    "Income": "Average_Income",
    "Age": "Average_Age",
    "MntWines": "Average_Wine_Spending",
    "NumWebPurchases": "Average_Web_Purchases",
    "NumStorePurchases": "Average_Store_Purchases"
})
print(grouped)

KeyError: "Column(s) ['MntWines'] do not exist"

<small>30. Create a Pivot Table with: Index = Education and Columns = Response and Values = Number of customer

In [ ]:
pivot_table = pd.pivot_table(df,
                             index="Education",
                             columns="Response",
                             values="No",
                             aggfunc="count",
                             fill_value=0)

pivot_table