Filename : notebook_02.ipynb <br>
Description : Pandas usage exampels

---

In [3]:
import numpy as np
import pandas as pd

print(pd.__version__)

2.3.1

---

1. Pandas Basic

In [4]:
### Creating Series ###

## Example 1: From List
scores = [85, 90, 78, 92]
s = pd.Series(scores)
print(s)                                            # Access entire series
print("The first element is", s[3])                 # Access single element

## Example 2: From Dictionary
scores = {
    "Alice": 85,
    "Bob": 90,
    "Charlie": 78
}
s = pd.Series(scores)
print(s)                                            # Access entire series
print("The second element is", ["Bob"])             # Access single element


## Example 3: From .csv (or .xlsx)
s = pd.read_csv("data_series.csv")["S1"]         
print(s)
print(type(s))

0    85
1    90
2    78
3    92
dtype: int64
The first element is 92
Alice      85
Bob        90
Charlie    78
dtype: int64
The second element is ['Bob']
0    0.242507
1    0.958693
2    0.850046
3    0.734946
4    0.937264
5    0.316667
6    0.300098
7    0.452212
8    0.458958
9    0.036284
Name: S1, dtype: float64
<class 'pandas.core.series.Series'>

In [5]:
### Creating DataFrames ###

## Example 1: From List
data = [
    ["Alice", 25, 85],
    ["Bob", 30, 90],
    ["Charlie", 22, 78]
]
df = pd.DataFrame(
    data,
    columns=["Name", "Age", "Score"]
)
print(df)

## Example 2: From Dictionary
data = {
    "Name": ["Brad", "Cuper", "Lisa"],
    "Age": [25, 30, 22],
    "Score": [85, 90, 78]
}
df = pd.DataFrame(data)
print(df)


## Example 3: From .csv (or .xlsx)
df = pd.read_csv("data_dataframe.csv")         
print(df)
print(type(df))

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   22     78
    Name  Age  Score
0   Brad   25     85
1  Cuper   30     90
2   Lisa   22     78
       S1  S2   S3    S4  S5
0  0.2425  11  Yes  9.28   0
1  0.9587  33   No  2.47   1
2  0.8500  67  Yes  2.31   0
3  0.7349  36  Yes  0.62   1
4  0.9373  58   No  7.13   1
5  0.3167  80   No  4.52   1
6  0.3001  71   No  2.18   1
7  0.4522  71  Yes  6.68   0
8  0.4590  99   No  5.46   0
9  0.0363  12   No  0.17   1
<class 'pandas.core.frame.DataFrame'>

In [6]:
### Inspecting data ###

df = pd.read_csv("iris.csv")  
df.head()
# df.tail()
# df.info()
# df.describe()

   sepal_length  sepal_width  petal_length  petal_width   iris_class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

---

2. Data Selection & Indexing

In [7]:
### Selecting columns ###

df = pd.read_csv("iris.csv") 
# df['sepal_width']
# df['sepal_length']

df[['sepal_width', 'sepal_length']]
# Take Note
# df['column']                 → Series
# df[['column1', 'column2']]   → DataFrame

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
..           ...           ...
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

In [8]:
### Row selection ###

## Example 1: .iloc[]
df = pd.read_csv("iris.csv") 
df.iloc[0]
df.iloc[0, 1]
df.iloc[[0],[1]]
df.iloc[0:5, 0:3]
df.iloc[5:10, 3:5]


## Example 2: .loc[]
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28],
    "Score": [85, 90, 78, 92]
}, index=["A", "B", "C", "D"])
print(df)
print()
print(df.loc[["A"]])
print()
print(df.loc["A", "Name"])
print()
print(df.loc["B"]["Score"])                         # OK but not good coding style


## Example 2.1: .loc[] with number index
df = pd.read_csv("iris.csv") 
print(df.loc[0,"sepal_width"])
print(df.loc[0]["sepal_width"])                     # OK but not good coding style

      Name  Age  Score
A    Alice   25     85
B      Bob   30     90
C  Charlie   22     78
D    David   28     92

    Name  Age  Score
A  Alice   25     85

Alice

90
3.5
3.5

In [9]:
### Boolean filtering ###

df = pd.read_csv("iris.csv") 
df[df["sepal_length"] > 6]
df[df["sepal_width"] < 3]
df[(df["sepal_length"] > 7) & (df["petal_width"] < 2)]
df[(df["sepal_length"] > 7) | (df["petal_width"] > 2)]
df[df["sepal_length"].between(5, 6)]
df[df["iris_class"] == "Iris-setosa"]
df[df["iris_class"].isin(["Iris-setosa", "Iris-versicolor"])]
df.loc[df["sepal_length"] > 6, ["sepal_length", "sepal_width", "iris_class"]]

     sepal_length  sepal_width       iris_class
50            7.0          3.2  Iris-versicolor
51            6.4          3.2  Iris-versicolor
52            6.9          3.1  Iris-versicolor
54            6.5          2.8  Iris-versicolor
56            6.3          3.3  Iris-versicolor
..            ...          ...              ...
144           6.7          3.3   Iris-virginica
145           6.7          3.0   Iris-virginica
146           6.3          2.5   Iris-virginica
147           6.5          3.0   Iris-virginica
148           6.2          3.4   Iris-virginica

[61 rows x 3 columns]

In [10]:
### Setting index ###

df = pd.DataFrame({
    "ID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Score": [85, 90, 78, 92]
})
print(df)

df2 = df.set_index("ID")
print(df2)

df2 = df.reset_index()
print(df2)

    ID     Name  Age  Score
0  101    Alice   20     85
1  102      Bob   21     90
2  103  Charlie   19     78
3  104    David   22     92
        Name  Age  Score
ID
101    Alice   20     85
102      Bob   21     90
103  Charlie   19     78
104    David   22     92
   index   ID     Name  Age  Score
0      0  101    Alice   20     85
1      1  102      Bob   21     90
2      2  103  Charlie   19     78
3      3  104    David   22     92

---

3. Data Cleaning

In [11]:
### Handling missing values ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, None, 22, 28],
    "Score": [85, 90, None, 92]
})
print(df)
print()

## Example 1: .isnull()
print(df.isna())
print()
print(df.isna().sum())
print()

## Example 2: .dropna()
df2 = df.dropna()
print(df2)
print()

df3 = df.dropna(subset=["Age"])
print(df3)
print()


## Example 3: .fillna()
df = df.fillna(0)
print(df)
print()

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Score"] = df["Score"].fillna(df["Score"].mean())
print(df)
print()

df2 = df.fillna({
    "Age": df["Age"].mean(),
    "Score": df["Score"].mean()
})
print(df2)

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   NaN   90.0
2  Charlie  22.0    NaN
3    David  28.0   92.0

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

Name     0
Age      1
Score    1
dtype: int64

    Name   Age  Score
0  Alice  25.0   85.0
3  David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
2  Charlie  22.0    NaN
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

In [12]:
### Renaming & dropping columns ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Math": [85, 90, 78, 92],
    "English": [88, 85, 80, 95]
})
print(df)

## Example 1: .rename()
df2 = df.rename(columns={
    "Name": "Student_Name",
    "Math": "Math_Score",
    "English": "English_Score"
})
print(df2)

## Example 2: .drop()
df3 = df.drop(columns=["Age", "English"])
print(df3)

df4 = df.drop("English", axis=1)
print(df4)

      Name  Age  Math  English
0    Alice   20    85       88
1      Bob   21    90       85
2  Charlie   19    78       80
3    David   22    92       95
  Student_Name  Age  Math_Score  English_Score
0        Alice   20          85             88
1          Bob   21          90             85
2      Charlie   19          78             80
3        David   22          92             95
      Name  Math
0    Alice    85
1      Bob    90
2  Charlie    78
3    David    92
      Name  Age  Math
0    Alice   20    85
1      Bob   21    90
2  Charlie   19    78
3    David   22    92

In [13]:
### Replace Values ###

## Example 1: .replace()
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Gender": ["F", "M", "M", "F"],
    "Grade": ["A", "B", "A", "C"]
})
print(df)
print()

# df["Gender"] = df["Gender"].replace("F", "Female")
# print(df)

# df["Grade"] = df["Grade"].replace({
#     "A": "Excellent",
#     "B": "Good",
#     "C": "Average"
# })
# print(df)

df = df.replace({
    "F": "Female",
    "M": "Male"
})
print(df)

# Important .replace != .fillna()
# df["Age"] = df["Age"].replace(0, 25)          # Two parameters needed
# df["Age"] = df["Age"].fillna(25)              # Single parameter needed

      Name Gender Grade
0    Alice      F     A
1      Bob      M     B
2  Charlie      M     A
3    David      F     C

      Name  Gender Grade
0    Alice  Female     A
1      Bob    Male     B
2  Charlie    Male     A
3    David  Female     C

In [14]:
### Detecting duplicates ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Bob", "David", "Alice"],
    "Age": [20, 21, 22, 21, 23, 20],
    "Score": [85, 90, 78, 90, 92, 85]
})
print(df)
print()

## Example 1: .duplicate()
print(df.duplicated())
print(df.duplicated().sum())

duplicates = df[df.duplicated()]
print(duplicates)

df2 = df.drop_duplicates()
print(df2)

df2 = df.drop_duplicates().reset_index(drop=True)           # Drop duplicate usually use with reset index in practice
print(df2)

print(df.duplicated(subset=["Name"]))

      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3      Bob   21     90
4    David   23     92
5    Alice   20     85

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
2
    Name  Age  Score
3    Bob   21     90
5  Alice   20     85
      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
4    David   23     92
      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3    David   23     92
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [15]:
### Type conversion ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": ["20", "21", "22"],
    "Score": ["85", "90", "78"],
    "Pass": [1, 1, 0]
})
print(df)
print(df.dtypes)

df["Name"] = df["Name"].astype(str)
df["Age"] = df["Age"].astype(int)
df["Score"] = df["Score"].astype(float)
df["Pass"] = df["Pass"].astype(bool)
print(df)
print(df.dtypes)

      Name Age Score  Pass
0    Alice  20    85     1
1      Bob  21    90     1
2  Charlie  22    78     0
Name     object
Age      object
Score    object
Pass      int64
dtype: object
      Name  Age  Score   Pass
0    Alice   20   85.0   True
1      Bob   21   90.0   True
2  Charlie   22   78.0  False
Name      object
Age        int64
Score    float64
Pass        bool
dtype: object

---

4. Transformation & Aggregation

In [16]:
### Applying functions ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Gender": ["Female", "Male", "Male"],
    "Age": [20, 25, 30],
    "Score": [80, 90, 75]
})
print(df)

# Example 1: .map()
# df["Score"] = df["Score"].map(lambda x: x + 1)      # Apply on each value
# print(df)

# df["Gender"] = df["Gender"].map({
#     "Male": 1,
#     "Female": 0
# })
# print(df)

# Example 2: .apply()
# df["Score"] = df["Score"].apply(lambda x: x + 5)
# print(df)

def add_bonus(x):
    return x + 5
df["Score"] = df["Score"].map(add_bonus)
print(df)

      Name  Gender  Age  Score
0    Alice  Female   20     80
1      Bob    Male   25     90
2  Charlie    Male   30     75
      Name  Gender  Age  Score
0    Alice  Female   20     85
1      Bob    Male   25     95
2  Charlie    Male   30     80

In [17]:
### GroupBy operations ###
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales', 'IT', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David',
                 'Eve', 'Frank', 'George', 'Helen'],
    'Salary': [50000, 60000, 45000, 48000, 55000, 65000, 52000, 70000],
    'Bonus': [5000, 6000, 4000, 4500, 5500, 6500, 5200, 7000]
}
df = pd.DataFrame(data)
print(df)

df.groupby('Department')['Salary'].mean()           # groupby() does not calculate anything by itself.
df.groupby('Department')['Salary'].sum()
df.groupby('Department')[['Salary', 'Bonus']].sum()
df.groupby('Department')['Salary'].agg(
    ['mean', 'max', 'min']
)
df.groupby('Department').agg({
    'Salary': ['mean', 'max'],
    'Bonus': ['sum', 'mean']
})

  Department Employee  Salary  Bonus
0         IT    Alice   50000   5000
1         IT      Bob   60000   6000
2         HR  Charlie   45000   4000
3         HR    David   48000   4500
4      Sales      Eve   55000   5500
5      Sales    Frank   65000   6500
6         IT   George   52000   5200
7      Sales    Helen   70000   7000

                  Salary         Bonus
                    mean    max    sum         mean
Department
HR          46500.000000  48000   8500  4250.000000
IT          54000.000000  60000  16200  5400.000000
Sales       63333.333333  70000  19000  6333.333333

In [18]:
### Pivot tables ###	
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales', 'IT', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David',
                 'Eve', 'Frank', 'George', 'Helen'],
    'Salary': [50000, 60000, 45000, 48000, 55000, 65000, 52000, 70000],
    'Bonus': [5000, 6000, 4000, 4500, 5500, 6500, 5200, 7000]
}
df = pd.DataFrame(data)
print(df)

# values   → What do I want to calculate?
# index    → How do I group the rows?
# aggfunc  → How do I summarize?
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc='mean'
)

# Columns  → How do I separate each value to single column?
df['Gender'] = [
    'F', 'M', 'M', 'F',
    'F', 'M', 'M', 'F'
]
print(df)
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='mean'
)

  Department Employee  Salary  Bonus
0         IT    Alice   50000   5000
1         IT      Bob   60000   6000
2         HR  Charlie   45000   4000
3         HR    David   48000   4500
4      Sales      Eve   55000   5500
5      Sales    Frank   65000   6500
6         IT   George   52000   5200
7      Sales    Helen   70000   7000
  Department Employee  Salary  Bonus Gender
0         IT    Alice   50000   5000      F
1         IT      Bob   60000   6000      M
2         HR  Charlie   45000   4000      M
3         HR    David   48000   4500      F
4      Sales      Eve   55000   5500      F
5      Sales    Frank   65000   6500      M
6         IT   George   52000   5200      M
7      Sales    Helen   70000   7000      F

Gender            F        M
Department
HR          48000.0  45000.0
IT          50000.0  56000.0
Sales       62500.0  65000.0

In [19]:
### Sorting ###
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Sales'],
    'Salary': [60000, 45000, 70000, 52000, 55000]
}
df = pd.DataFrame(data)
print(df)


df.sort_values('Salary')                            # Sorting do not change order in original dataframe!
df.sort_values('Salary', ascending=False)

df.sort_values(
    by=['Department', 'Salary'],
    ascending=[True, False]
)

df2 = df.copy()
df2.index = [103, 101, 105, 102, 104]
print(df2)

  Employee Department  Salary
0    Alice         IT   60000
1      Bob         HR   45000
2  Charlie      Sales   70000
3    David         IT   52000
4      Eve      Sales   55000
    Employee Department  Salary
103    Alice         IT   60000
101      Bob         HR   45000
105  Charlie      Sales   70000
102    David         IT   52000
104      Eve      Sales   55000

---

5. Merging and Reshaping Data

In [20]:
### Concatenation ###

## Example 1: Extend Rows
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Jane', 'Bob'],
    'Score': [80, 75, 90]
})
df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['Alice', 'David', 'Emma'],
    'Score': [85, 70, 95]
})

df = pd.concat([df1, df2], axis=0)                              # axis=0 is default, can omit it
df = pd.concat([df1, df2], axis=0, ignore_index=True)           # Recommend to reset index 
print(df)



## Example 2 : Extend columns
name = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob']
})
score = pd.DataFrame({
    'Score': [80, 75, 90]
})
df = pd.concat([name, score], axis=1)                           # axis=1 cannot omit for extending columns
print(df)



## Example 3: Concat different dataframe
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['John', 'Jane']
})
df2 = pd.DataFrame({
    'ID': [3, 4],
    'Score': [90, 80]
})
result = pd.concat([df1, df2], ignore_index=True)
print(result)

   ID   Name  Score
0   1   John     80
1   2   Jane     75
2   3    Bob     90
3   4  Alice     85
4   5  David     70
5   6   Emma     95
   Name  Score
0  John     80
1  Jane     75
2   Bob     90
   ID  Name  Score
0   1  John    NaN
1   2  Jane    NaN
2   3   NaN   90.0
3   4   NaN   80.0

In [21]:
### Merging/Joining ###

##Example 1: Merge() 
# students = pd.DataFrame({
#     'student_id': [101, 102, 103, 104],
#     'name': ['Alice', 'Bob', 'Charlie', 'David']
# })
# scores = pd.DataFrame({
#     'student_id': [101, 102, 103, 105],
#     'score': [85, 72, 90, 65]
# })

# result = pd.merge(students, scores, on='student_id', how='inner')             # If key is in column
# result = pd.merge(students, scores, on='student_id', how='outer')
# result = pd.merge(students, scores, on='student_id', how='left')
# result = pd.merge(students, scores, on='student_id', how='right')
# print(result)


##Example 2: Join() 
students = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David']
}, index=[101, 102, 103, 104])

scores = pd.DataFrame({
    'score': [85, 72, 90, 65]
}, index=[101, 102, 103, 105])

result = students.join(scores)                                                  # If key is in index
result = students.join(scores, how='right')                     
result = students.join(scores, how='inner')
result = students.join(scores, how='outer')
print(result)

        name  score
101    Alice   85.0
102      Bob   72.0
103  Charlie   90.0
104    David    NaN
105      NaN   65.0

In [22]:
### Reshaping ###

## Example 1: .melt()
# df = pd.DataFrame({
#     'Name': ['John', 'Jane', 'Bob'],
#     'Math': [80, 75, 90],
#     'English': [85, 80, 88],
#     'Science': [90, 85, 92]
# })
# df_long = df.melt(
#     id_vars='Name',                               # Remaining column 
#     var_name='Subject',                           # New column name of original columns
#     value_name='Score'                            # New column for the data
# )
# print(df_long)



# Example 2: .stack() and .unstack
df = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob'],
    'Math': [80, 75, 90],
    'English': [85, 80, 88],
    'Science': [90, 85, 92]
})
df = df.set_index('Name')
print(df)

result = df.stack()                                # Columns convert to Index 
print(result)

result = result.unstack()                           # Index convert to Columns
print(result)

      Math  English  Science
Name
John    80       85       90
Jane    75       80       85
Bob     90       88       92
Name
John  Math       80
      English    85
      Science    90
Jane  Math       75
      English    80
      Science    85
Bob   Math       90
      English    88
      Science    92
dtype: int64
      Math  English  Science
Name
John    80       85       90
Jane    75       80       85
Bob     90       88       92

---